services:
  postgres-test:
    image: postgres:16
    environment:
      - POSTGRES_USER=marty_test
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=marty_test
    ports:
      - "5432:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U marty_test"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - test_network

  redis-test:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_test_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - test_network

volumes:
  postgres_test_data:
  redis_test_data:

networks:
  test_network:
    driver: bridge
