"""add opted_out field to customer for 10DLC compliance

Revision ID: 22a6418060c5
Revises: d82c5d22c9f7
Create Date: 2025-07-17 10:10:35.081093

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "22a6418060c5"
down_revision: str | Sequence[str] | None = "d82c5d22c9f7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "books",
        "title",
        existing_type=sa.VARCHAR(length=500),
        type_=sa.Text(),
        existing_nullable=False,
    )
    op.alter_column(
        "books",
        "author",
        existing_type=sa.VARCHAR(length=500),
        type_=sa.Text(),
        existing_nullable=True,
    )
    op.alter_column(
        "books",
        "publisher",
        existing_type=sa.VARCHAR(length=200),
        type_=sa.Text(),
        existing_nullable=True,
    )
    op.alter_column(
        "books",
        "bookshop_url",
        existing_type=sa.VARCHAR(length=500),
        type_=sa.Text(),
        existing_nullable=True,
    )
    op.add_column("customers", sa.Column("opted_out", sa.Boolean(), nullable=False))
    op.alter_column(
        "customers",
        "email",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.Text(),
        existing_nullable=True,
    )
    op.drop_column("customers", "first_name")
    op.drop_column("customers", "last_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "customers", sa.Column("last_name", sa.VARCHAR(length=100), nullable=True)
    )
    op.add_column(
        "customers", sa.Column("first_name", sa.VARCHAR(length=100), nullable=True)
    )
    op.alter_column(
        "customers",
        "email",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=255),
        existing_nullable=True,
    )
    op.drop_column("customers", "opted_out")
    op.alter_column(
        "books",
        "bookshop_url",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=500),
        existing_nullable=True,
    )
    op.alter_column(
        "books",
        "publisher",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=200),
        existing_nullable=True,
    )
    op.alter_column(
        "books",
        "author",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=500),
        existing_nullable=True,
    )
    op.alter_column(
        "books",
        "title",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=500),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
